Revert "adb: add transport benchmark."
This reverts commit ef0ed378d4172e2d5333b0bc4434cdd33dc0b511.

Reason for revert: Breaks aosp-master renderscript and sdk_mac:
  error: system/core/adb/Android.bp:199:19: unrecognized property "host_supported"

Change-Id: Ifd75921dcdf5dce57f98833a913540914984b293